language: android
jdk: oraclejdk8
sudo: true
cache:
  directories:
  - "${TRAVIS_BUILD_DIR}/gradle/caches/"
  - "${TRAVIS_BUILD_DIR}/gradle/wrapper/dists/"
env:
  global:
  - API_LEVEL=25
  - ANDROID_EMULATOR_API_LEVEL=23
  - ANDROID_BUILD_TOOLS_VERSION=25.0.2
  - ANDROID_ABI=google_apis/armeabi-v7a
  - ADB_INSTALL_TIMEOUT=20
  - ANDROID_TARGET=android-22
  - ANDROID_TAG=google_apis
android:
  components:
  - tools
  - platform-tools
  - tools
  - build-tools-$ANDROID_BUILD_TOOLS_VERSION
  - android-$API_LEVEL
  - android-$ANDROID_EMULATOR_API_LEVEL
  - extra-android-support
  - extra-google-m2repository
  - extra-android-m2repository
  - addon-google_apis-google-$API_LEVEL
  - addon-google_apis-google-$ANDROID_EMULATOR_API_LEVEL
  - sys-img-armeabi-v7a-google_apis-$ANDROID_EMULATOR_API_LEVEL
before_install:
- openssl aes-256-cbc -K $encrypted_919dbe00e59e_key -iv $encrypted_919dbe00e59e_iv
  -in google-services.json.enc -out app/google-services.json -d
- android list targets
- chmod +x gradlew
- echo no | android create avd --force -n test -t "android-"$ANDROID_EMULATOR_API_LEVEL
  --abi $ANDROID_ABI --tag $ANDROID_TAG
- emulator -avd test -no-skin -no-window &
- android-wait-for-emulator
- adb shell input keyevent 82 &
script: travis_retry travis_wait ./gradlew connectedAndroidTest
after_success:
- mv ./app/build/outputs/apk/app-debug.apk ./app/build/outputs/apk/CheesecakeUtilities_Tiles-debug.apk
- ls ./app/build/outputs/apk/
after_failure:
- ls $TRAVIS_BUILD_DIR/app/build/outputs/androidTest-results/connected/
- cat $TRAVIS_BUILD_DIR/app/build/outputs/androidTest-results/connected/TEST-*.xml
deploy:
  provider: releases
  api_key: "$OAUTH_KEY"
  file: "./app/build/outputs/apk/CheesecakeUtilities_Tiles-debug.apk"
  skip_cleanup: true
  on:
    tags: true
notifications:
  irc:
    channels:
    - chat.freenode.net#itachi1706mc
    - irc.esper.net#itachi1706
    on_success: always
    on_failure: always
    template:
    - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{commit_subject}"
    - 'Build Status : %{message}'
    - 'Change view : %{compare_url}'
    - 'Build details : %{build_url}'
  email:
    recipients:
    - "$PRIVATE_EMAIL"
    on_success: change
    on_failure: always
  slack:
    secure: mWY8ZsVcNJalO7rxN4QvKzjpU0e1nDtlONsPxOin0We++vN6BKXBjwQYT/5sVGyLjDBa8GJ2Nn8eKX5UjIzvVqJ7XFD2j5iElkJSoteIjbK3uNQM8Gl+l2O/BXelGFV8XD1e0AKfq3NuEKTOZ09DGPBNZu50z+P89/K2dk26CZySNY+bK/Q4z/K7nMPat/BSwI1fxek3vM8fz3d6O1Qt3SxN7d+smx6wJbczTsA2I35M7eNiQHZa6Jhg2u5KlZlMBKQnuCIM0P+WyM1cFeHBVbv4g0yCQSNULbtRDFOni+65VJSwL1VNTmLdu+ch1ez3iUiKQTnJIJa2+svk4pT4zEyCqKy4oq3zXJ/lB/MfPr6tyPNc7nypprmd6onLGjCWDWpQuVbjgLk1cTGw8BHJvRcb6+Dzw3VvBzq9UqrSJIwRgOWGr3DBMk0zP+HZxCKGXcCURUXNxfylrfvqhgMfTY5QVkjwwZlJaqUC7iZC+sJWrMzP3SaICSQ4BBLaaGRBhHlreW+dpI+VsMtsBNfa7jhtNvzHDJa6ceImm1wyBQJ+pvcb7jTsvkSPcjw40QFkxbX+dahw172UyAb6yT/54wqAtnUE8fHnmZG2nmrQo453bRPZLlZKPg0HHpwuSCfRng1uNTyEwGCmKNab6PDHg1w/DwBbo76pn5UCC8HL1xY=
